// apps/ssr-vue/app/app.vue
<script setup lang="ts">
// biome-ignore lint/correctness/noUnusedImports: used in template
import { createGlowTour, GlowTourDefault } from "@glowhop/vue-tour";

const tour = createGlowTour();
const workflow = tour
  .create("welcome")
  .step({
    content: "This step is rendered by the SSR verification harness.",
    target: "#tour-target",
    title: "Step one",
  })
  .step({
    content: "Clicking advance again finishes the tour.",
    target: "#tour-trigger",
    title: "Step two",
  })
  .build();

// biome-ignore lint/correctness/noUnusedVariables: used in template
function start() {
  void tour.run(workflow);
}
</script>

<template>
  <div style="padding: 20px">
    <h1>Glow Tour - SSR Vue (Nuxt) verification harness</h1>
    <p id="tour-target">This is the tour target element.</p>
    <button id="tour-trigger" type="button" @click="start">Start tour</button>
  </div>
  <GlowTourDefault :tour="tour" />
</template>

// examples/angular/src/app.component.ts
import { Component } from "@angular/core";
import "@glowhop/styles-tour/default.css";
import { createGlowTour, GlowTourDefault } from "@glowhop/angular-tour";

@Component({
  standalone: true,
  imports: [GlowTourDefault],
  selector: "app-root",
  template: `
    <div style="padding: 20px">
      <h1>Glow Tour - Angular Example</h1>
      <button
        id="welcome"
        type="button"
        (click)="start()"
        style="padding: 10px 20px; font-size: 16px"
      >
        Start tour
      </button>
    </div>
    <glow-tour-default [tour]="tour" />
  `,
})
export class AppComponent {
  readonly tour = createGlowTour();
  readonly workflow = this.tour
    .create("welcome")
    .step({ target: "#welcome", title: "Welcome", content: "Hello world!" })
    .build();

  start() {
    void this.tour.run(this.workflow);
  }
}
