// packages/angular/src/angular.browser.ts
import "@angular/compiler";
import "zone.js";
import { afterAll, beforeAll, beforeEach, describe, test } from "bun:test";
import assert from "node:assert/strict";
import { Component, ErrorHandler, type OnInit } from "@angular/core";
import { bootstrapApplication } from "@angular/platform-browser";
import { Window } from "happy-dom";
import { runAdapterAcceptance } from "../../../scripts/adapter-acceptance";
import * as runtime from "./public-api";

let window: Window;

beforeAll(() => {
  window = new Window();
  Object.assign(globalThis, {
    Event: window.Event,
    Element: window.Element,
    HTMLElement: window.HTMLElement,
    KeyboardEvent: window.KeyboardEvent,
    MouseEvent: window.MouseEvent,
    MutationObserver: window.MutationObserver,
    Node: window.Node,
    ResizeObserver: window.ResizeObserver,
    SVGSVGElement: window.SVGSVGElement,
    cancelAnimationFrame: window.cancelAnimationFrame.bind(window),
    document: window.document,
    requestAnimationFrame: window.requestAnimationFrame.bind(window),
    window,
  });
});

beforeEach(() => {
  document.body.replaceChildren();
});

afterAll(() => {
  window.close();
});

async function settle() {
  await Promise.resolve();
  await Promise.resolve();
  await new Promise<void>((resolve) => window.setTimeout(resolve, 0));
}

describe("angular adapter browser behavior", () => {
  test("exposes reactive tour state to descendants", async () => {
    const tour = runtime.createGlowTour();
    const target = document.createElement("button");
    document.body.append(target);

    @Component({
      selector: "angular-tour-state-observer",
      standalone: true,
      template: `<output>{{ state()?.status }}:{{ state()?.currentStepIndex }}</output>`,
    })
    class TourStateObserver {
      readonly state = runtime.injectGlowTour();
    }

    @Component({
      selector: "angular-tour-state-harness",
      standalone: true,
      imports: [runtime.GlowTourRoot, TourStateObserver],
      template: `
        <glow-tour-root [tour]="tour">
          <angular-tour-state-observer />
        </glow-tour-root>
      `,
    })
    class TourStateHarness {
      readonly tour = tour;
    }

    document.body.append(document.createElement("angular-tour-state-harness"));
    const app = await bootstrapApplication(TourStateHarness);
    const workflow = tour
      .create("reactive state")
      .step({ content: "First", target, title: "First" })
      .step({ content: "Second", target, title: "Second" })
      .build();
    await tour.run(workflow);
    await settle();
    app.tick();
    assert.equal(document.querySelector("output")?.textContent?.trim(), "active:0");
    await tour.goNext();
    await settle();
    app.tick();
    assert.equal(document.querySelector("output")?.textContent?.trim(), "active:1");
    await app.destroy();
  });

  test("connects a root during Angular initialization and releases it on destruction", async () => {
    const tour = runtime.createGlowTour();
    const target = document.createElement("button");
    document.body.append(target);

    @Component({
      selector: "angular-root-lifecycle",
      standalone: true,
      imports: [
        runtime.GlowTourRoot,
        runtime.GlowTourPopover,
        runtime.GlowTourHeader,
        runtime.GlowTourContent,
        runtime.GlowTourFooter,
        runtime.GlowTourBackTrigger,
        runtime.GlowTourNextTrigger,
        runtime.GlowTourCancelTrigger,
        runtime.GlowTourOverlay,
        runtime.GlowTourPointer,
      ],
      template: `
        <glow-tour-root [tour]="tour" idPrefix="angular">
          <glow-tour-overlay />
          <glow-tour-pointer />
          <glow-tour-popover>
            <glow-tour-header />
            <glow-tour-content />
            <glow-tour-footer>
              <glow-tour-back-trigger />
              <glow-tour-next-trigger />
              <glow-tour-cancel-trigger />
            </glow-tour-footer>
          </glow-tour-popover>
        </glow-tour-root>
      `,
    })
    class LifecycleHarness {
      readonly tour = tour;
    }

    document.body.append(document.createElement("angular-root-lifecycle"));
    const app = await bootstrapApplication(LifecycleHarness);
    await settle();
    app.tick();

    const root = document.querySelector<HTMLElement>("[data-glow-tour-root]");
    const popover = document.querySelector<HTMLElement>("[data-glow-tour-popover]");
    assert.equal(root?.id, "angular-root");
    assert.equal(popover?.id, "angular-popover");
    assert.equal(popover?.getAttribute("aria-labelledby"), "angular-title");
    assert.equal(popover?.getAttribute("aria-describedby"), "angular-description");

    const workflow = tour
      .create("angular lifecycle")
      .step({ content: "First content", target, title: "First title" })
      .step({ content: "Second content", target, title: "Second title" })
      .build();
    await tour.run(workflow);
    await settle();
    app.tick();
    assert.match(document.body.textContent ?? "", /First title/);
    assert.match(document.body.textContent ?? "", /First content/);
    const firstBack = document.querySelector<HTMLButtonElement>("[data-glow-tour-back-trigger]");
    assert.equal(firstBack?.disabled, true);
    assert.equal(firstBack?.getAttribute("aria-disabled"), "true");

    tour.updateCurrentStep((props) => ({
      ...props,
      content: "Updated content",
      hideFooter: true,
      hideNextButton: true,
      title: "Updated title",
    }));
    await settle();
    app.tick();
    assert.match(document.body.textContent ?? "", /Updated title/);
    assert.match(document.body.textContent ?? "", /Updated content/);
    assert.equal(document.querySelector("[data-glow-tour-footer]"), null);
    assert.equal(document.querySelector("[data-glow-tour-next-trigger]"), null);

    tour.updateCurrentStep((props) => ({ ...props, hideFooter: false, hideNextButton: false }));
    await settle();
    app.tick();

    const next = document.querySelector<HTMLButtonElement>("[data-glow-tour-next-trigger]");
    assert.equal(next?.getAttribute("aria-controls"), "angular-popover");
    assert.equal(next?.disabled, false);
    next?.dispatchEvent(new MouseEvent("click", { bubbles: true, cancelable: true }));
    await settle();
    assert.equal(tour.state.get().currentStepIndex, 1);

    await app.destroy();
    await assert.rejects(() => tour.run(tour.create("released").build()), /connected root/i);
  });

  test("reconnects only the latest Angular input pair and isolates nearest nested roots", async () => {
    const first = runtime.createGlowTour();
    const second = runtime.createGlowTour();
    const inner = runtime.createGlowTour();
    const outerTarget = document.createElement("button");
    const innerTarget = document.createElement("button");
    document.body.append(outerTarget, innerTarget);

    @Component({
      selector: "angular-root-replacement",
      standalone: true,
      imports: [runtime.GlowTourRoot, runtime.GlowTourNextTrigger],
      template: `
        <glow-tour-root [tour]="tour" [idPrefix]="idPrefix">
          <glow-tour-next-trigger />
          <glow-tour-root [tour]="inner" idPrefix="inner">
            <glow-tour-next-trigger />
          </glow-tour-root>
        </glow-tour-root>
      `,
    })
    class ReplacementHarness {
      tour = first;
      idPrefix = "first";
      readonly inner = inner;
    }

    document.body.append(document.createElement("angular-root-replacement"));
    const app = await bootstrapApplication(ReplacementHarness);
    await settle();
    app.tick();
    assert.equal(document.querySelector("[data-glow-tour-root]")?.id, "first-root");

    const harness = app.components[0]?.instance;
    assert.ok(harness instanceof ReplacementHarness);
    harness.tour = second;
    harness.idPrefix = "second";
    app.tick();
    await settle();
    assert.equal(document.querySelector("[data-glow-tour-root]")?.id, "second-root");
    await assert.rejects(
      () => first.run(first.create("first released").build()),
      /connected root/i,
    );

    const workflow = (tour: typeof second, target: HTMLElement, name: string) =>
      tour
        .create(name)
        .step({ content: "One", target, title: "One" })
        .step({ content: "Two", target, title: "Two" })
        .build();
    await second.run(workflow(second, outerTarget, "outer"));
    await inner.run(workflow(inner, innerTarget, "inner"));
    const [outerNext, innerNext] = Array.from(
      document.querySelectorAll<HTMLButtonElement>("[data-glow-tour-next-trigger]"),
    );
    assert.equal(innerNext?.disabled, false);
    innerNext?.dispatchEvent(new MouseEvent("click", { bubbles: true, cancelable: true }));
    await settle();
    assert.equal(inner.state.get().currentStepIndex, 1);
    assert.equal(second.state.get().currentStepIndex, 0);
    assert.notEqual(
      outerNext?.getAttribute("aria-controls"),
      innerNext?.getAttribute("aria-controls"),
    );
    await app.destroy();
  });

  test("keeps sibling root controls, IDs, and delegated commands isolated", async () => {
    const first = runtime.createGlowTour();
    const second = runtime.createGlowTour();
    const firstTarget = document.createElement("button");
    const secondTarget = document.createElement("button");
    document.body.append(firstTarget, secondTarget);

    @Component({
      selector: "angular-sibling-roots",
      standalone: true,
      imports: [runtime.GlowTourRoot, runtime.GlowTourPopover, runtime.GlowTourNextTrigger],
      template: `
        <glow-tour-root [tour]="first" idPrefix="first-sibling">
          <glow-tour-popover />
          <glow-tour-next-trigger />
        </glow-tour-root>
        <glow-tour-root [tour]="second" idPrefix="second-sibling">
          <glow-tour-popover />
          <glow-tour-next-trigger />
        </glow-tour-root>
      `,
    })
    class SiblingRootsHarness {
      readonly first = first;
      readonly second = second;
    }

    document.body.append(document.createElement("angular-sibling-roots"));
    const app = await bootstrapApplication(SiblingRootsHarness);
    const workflow = (tour: typeof first, target: HTMLElement, name: string) =>
      tour
        .create(name)
        .step({ content: `${name} one`, target, title: `${name} one` })
        .step({ content: `${name} two`, target, title: `${name} two` })
        .build();
    await first.run(workflow(first, firstTarget, "first"));
    await second.run(workflow(second, secondTarget, "second"));
    await settle();
    app.tick();

    const roots = Array.from(document.querySelectorAll<HTMLElement>("[data-glow-tour-root]"));
    const popovers = Array.from(document.querySelectorAll<HTMLElement>("[data-glow-tour-popover]"));
    const [firstNext, secondNext] = Array.from(
      document.querySelectorAll<HTMLButtonElement>("[data-glow-tour-next-trigger]"),
    );
    assert.deepEqual(
      roots.map((root) => root.id),
      ["first-sibling-root", "second-sibling-root"],
    );
    assert.deepEqual(
      popovers.map((popover) => popover.id),
      ["first-sibling-popover", "second-sibling-popover"],
    );
    assert.equal(firstNext?.getAttribute("aria-controls"), "first-sibling-popover");
    assert.equal(secondNext?.getAttribute("aria-controls"), "second-sibling-popover");

    const secondControl = secondNext;
    const secondRootId = roots[1]?.id;
    const secondPopoverId = popovers[1]?.id;
    firstNext?.dispatchEvent(new MouseEvent("click", { bubbles: true, cancelable: true }));
    await settle();

    assert.equal(first.state.get().currentStepIndex, 1);
    assert.equal(second.state.get().currentStepIndex, 0);
    assert.equal(secondNext, secondControl);
    assert.equal(secondNext?.isConnected, true);
    assert.equal(roots[1]?.id, secondRootId);
    assert.equal(popovers[1]?.id, secondPopoverId);
    assert.equal(secondNext?.getAttribute("aria-controls"), "second-sibling-popover");
    await app.destroy();
  });

  test("connects before a descendant Angular initialization can run its tour", async () => {
    const tour = runtime.createGlowTour();
    let started: Promise<void> | undefined;

    @Component({ selector: "angular-descendant-runner", standalone: true, template: "" })
    class DescendantRunner implements OnInit {
      ngOnInit() {
        started = tour.run(tour.create("descendant initialization").build());
      }
    }

    @Component({
      selector: "angular-descendant-root",
      standalone: true,
      imports: [runtime.GlowTourRoot, DescendantRunner],
      template: '<glow-tour-root [tour]="tour"><angular-descendant-runner /></glow-tour-root>',
    })
    class DescendantRootHarness {
      readonly tour = tour;
    }

    document.body.append(document.createElement("angular-descendant-root"));
    const app = await bootstrapApplication(DescendantRootHarness);
    assert.ok(started);
    await assert.doesNotReject(started);
    await app.destroy();
  });

  test("batches tour and idPrefix replacement into one Angular root lease", async () => {
    const bridgeSymbol = Symbol.for("@glowhop/core-tour/adapter-bridge/v1");
    const calls: string[] = [];
    const fakeTour = (name: string) => {
      const tour = { state: runtime.createGlowTour().state };
      Object.defineProperty(tour, bridgeSymbol, {
        value: {
          connectRoot: ({ idPrefix }: { idPrefix?: string }) => {
            const prefix = idPrefix ?? "glow-tour";
            calls.push(`connect:${name}:${prefix}`);
            return {
              bindOverlay: () => () => {},
              bindPointer: () => () => {},
              bindPopover: () => () => {},
              ids: {
                description: `${prefix}-description`,
                popover: `${prefix}-popover`,
                root: `${prefix}-root`,
                title: `${prefix}-title`,
              },
              release: () => calls.push(`release:${name}:${prefix}`),
            };
          },
          version: 1,
        },
      });
      return tour as ReturnType<typeof runtime.createGlowTour>;
    };
    const first = fakeTour("first");
    const second = fakeTour("second");

    @Component({
      selector: "angular-batched-root",
      standalone: true,
      imports: [runtime.GlowTourRoot],
      template: '<glow-tour-root [tour]="tour" [idPrefix]="idPrefix" />',
    })
    class BatchedRootHarness {
      idPrefix = "first-prefix";
      tour = first;
    }

    document.body.append(document.createElement("angular-batched-root"));
    const app = await bootstrapApplication(BatchedRootHarness);
    assert.deepEqual(calls, ["connect:first:first-prefix"]);
    calls.length = 0;
    const harness = app.components[0]?.instance;
    assert.ok(harness instanceof BatchedRootHarness);
    harness.tour = second;
    harness.idPrefix = "second-prefix";
    app.tick();
    await settle();
    assert.deepEqual(calls, ["release:first:first-prefix", "connect:second:second-prefix"]);
    await app.destroy();
  });

  test("binds controls inserted after a tour starts and applies its custom shortcut", async () => {
    const tour = runtime.createGlowTour();
    const target = document.createElement("button");
    document.body.append(target);

    @Component({
      selector: "angular-late-trigger",
      standalone: true,
      imports: [runtime.GlowTourRoot, runtime.GlowTourNextTrigger],
      template: `
        <glow-tour-root [tour]="tour">
          @if (showNext) { <glow-tour-next-trigger /> }
        </glow-tour-root>
      `,
    })
    class LateTriggerHarness {
      readonly tour = tour;
      showNext = false;
    }

    document.body.append(document.createElement("angular-late-trigger"));
    const app = await bootstrapApplication(LateTriggerHarness);
    const workflow = tour
      .create("late trigger")
      .step({
        content: "One",
        popover: { keyboardShortcuts: { next: ["N"] } },
        target,
        title: "One",
      })
      .step({ content: "Two", target, title: "Two" })
      .build();
    await tour.run(workflow);
    const harness = app.components[0]?.instance;
    assert.ok(harness instanceof LateTriggerHarness);
    harness.showNext = true;
    app.tick();
    await settle();
    const next = document.querySelector<HTMLButtonElement>("[data-glow-tour-next-trigger]");
    assert.equal(next?.getAttribute("aria-keyshortcuts"), "N");
    window.dispatchEvent(new window.KeyboardEvent("keydown", { key: "N" }));
    await settle();
    assert.equal(tour.state.get().currentStepIndex, 1);
    await app.destroy();
  });

  test("cleans a removed popover binding before registering its replacement", async () => {
    const bridgeSymbol = Symbol.for("@glowhop/core-tour/adapter-bridge/v1");
    const calls: string[] = [];
    const tour = { state: runtime.createGlowTour().state };
    Object.defineProperty(tour, bridgeSymbol, {
      value: {
        connectRoot: () => ({
          bindOverlay: () => () => {},
          bindPointer: () => () => {},
          bindPopover: () => {
            const id = calls.filter((entry) => entry.startsWith("bind")).length + 1;
            calls.push(`bind:${id}`);
            return () => calls.push(`release:${id}`);
          },
          ids: {
            description: "cleanup-description",
            popover: "cleanup-popover",
            root: "cleanup-root",
            title: "cleanup-title",
          },
          release: () => {},
        }),
        version: 1,
      },
    });

    @Component({
      selector: "angular-element-cleanup",
      standalone: true,
      imports: [runtime.GlowTourRoot, runtime.GlowTourPopover],
      template: `
        <glow-tour-root [tour]="tour">
          @if (showPopover) { <glow-tour-popover /> }
        </glow-tour-root>
      `,
    })
    class ElementCleanupHarness {
      readonly tour = tour as ReturnType<typeof runtime.createGlowTour>;
      showPopover = true;
    }

    document.body.append(document.createElement("angular-element-cleanup"));
    const app = await bootstrapApplication(ElementCleanupHarness);
    await settle();
    assert.deepEqual(calls, ["bind:1"]);
    const harness = app.components[0]?.instance;
    assert.ok(harness instanceof ElementCleanupHarness);
    harness.showPopover = false;
    app.tick();
    await settle();
    assert.deepEqual(calls, ["bind:1", "release:1"]);
    harness.showPopover = true;
    app.tick();
    await settle();
    assert.deepEqual(calls, ["bind:1", "release:1", "bind:2"]);
    await app.destroy();
  });

  test("reacts to dynamic trigger labels and consumer disabled bindings", async () => {
    const tour = runtime.createGlowTour();
    const target = document.createElement("button");
    document.body.append(target);

    @Component({
      selector: "angular-trigger-inputs",
      standalone: true,
      imports: [
        runtime.GlowTourRoot,
        runtime.GlowTourBackTrigger,
        runtime.GlowTourNextTrigger,
        runtime.GlowTourCancelTrigger,
      ],
      template: `
        <glow-tour-root [tour]="tour">
          <glow-tour-back-trigger [backLabel]="backLabel" [disabled]="disabled" />
          <glow-tour-next-trigger [finishLabel]="finishLabel" [nextLabel]="nextLabel" [disabled]="disabled" (click)="onNextClick($event)" />
          <glow-tour-cancel-trigger [ariaLabel]="cancelAria" [disabled]="disabled" />
          <glow-tour-cancel-trigger ariaLabel="Static cancel" data-static-cancel disabled />
        </glow-tour-root>
      `,
    })
    class TriggerInputsHarness {
      readonly tour = tour;
      backLabel = "Back one";
      cancelAria = "Cancel one";
      disabled = true;
      finishLabel = "Finish one";
      nextLabel = "Next one";
      preventNext = false;

      onNextClick(event: Event) {
        if (this.preventNext) event.preventDefault();
      }
    }

    document.body.append(document.createElement("angular-trigger-inputs"));
    const app = await bootstrapApplication(TriggerInputsHarness);
    const workflow = tour
      .create("dynamic trigger inputs")
      .step({ content: "One", target, title: "One" })
      .step({ content: "Two", target, title: "Two" })
      .build();
    await tour.run(workflow);
    await settle();
    app.tick();

    const next = document.querySelector<HTMLButtonElement>("[data-glow-tour-next-trigger]");
    const cancel = document.querySelector<HTMLButtonElement>("[data-glow-tour-cancel-trigger]");
    const staticCancel = document.querySelector<HTMLButtonElement>(
      "[data-static-cancel] [data-glow-tour-cancel-trigger]",
    );
    assert.equal(next?.textContent, "Next one");
    assert.equal(next?.disabled, true);
    assert.equal(next?.getAttribute("aria-disabled"), "true");
    assert.equal(next?.getAttribute("data-glow-tour-consumer-disabled"), "true");
    assert.equal(cancel?.textContent, "Cancel tour");
    assert.equal(cancel?.getAttribute("aria-label"), "Cancel one");
    assert.equal(staticCancel?.disabled, true);
    assert.equal(staticCancel?.getAttribute("aria-disabled"), "true");
    assert.equal(staticCancel?.getAttribute("data-glow-tour-consumer-disabled"), "true");

    next?.dispatchEvent(new MouseEvent("click", { bubbles: true, cancelable: true }));
    cancel?.dispatchEvent(new MouseEvent("click", { bubbles: true, cancelable: true }));
    await settle();
    assert.equal(tour.state.get().currentStepIndex, 0);
    assert.equal(tour.state.get().status, "active");

    const harness = app.components[0]?.instance;
    assert.ok(harness instanceof TriggerInputsHarness);
    harness.backLabel = "Back two";
    harness.cancelAria = "Cancel two";
    harness.disabled = false;
    harness.nextLabel = "Next two";
    app.tick();
    await settle();

    assert.equal(next?.textContent, "Next two");
    assert.equal(next?.disabled, false);
    assert.equal(next?.getAttribute("aria-disabled"), "false");
    assert.equal(next?.hasAttribute("data-glow-tour-consumer-disabled"), false);
    assert.equal(cancel?.getAttribute("aria-label"), "Cancel two");

    harness.preventNext = true;
    app.tick();
    next?.dispatchEvent(new MouseEvent("click", { bubbles: true, cancelable: true }));
    await settle();
    assert.equal(tour.state.get().currentStepIndex, 0);

    harness.preventNext = false;
    app.tick();
    next?.dispatchEvent(new MouseEvent("click", { bubbles: true, cancelable: true }));
    await settle();
    assert.equal(tour.state.get().currentStepIndex, 1);

    app.tick();
    const back = document.querySelector<HTMLButtonElement>("[data-glow-tour-back-trigger]");
    assert.equal(back?.textContent, "Back two");
    assert.equal(back?.disabled, false);
    assert.equal(next?.textContent, "Finish one");
    harness.finishLabel = "Finish two";
    harness.disabled = true;
    app.tick();
    await settle();
    assert.equal(next?.textContent, "Finish two");
    assert.equal(back?.disabled, true);
    assert.equal(cancel?.disabled, true);

    back?.dispatchEvent(new MouseEvent("click", { bubbles: true, cancelable: true }));
    cancel?.dispatchEvent(new MouseEvent("click", { bubbles: true, cancelable: true }));
    await settle();
    assert.equal(tour.state.get().currentStepIndex, 1);
    assert.equal(tour.state.get().status, "active");

    harness.disabled = false;
    app.tick();
    await settle();
    back?.dispatchEvent(new MouseEvent("click", { bubbles: true, cancelable: true }));
    await settle();
    assert.equal(tour.state.get().currentStepIndex, 0);

    cancel?.dispatchEvent(new MouseEvent("click", { bubbles: true, cancelable: true }));
    await settle();
    assert.equal(tour.state.get().status, "cancelled");
    await app.destroy();
  });

  test("reports a scoped-context error for a standalone descendant", async () => {
    @Component({
      selector: "angular-outside-root",
      standalone: true,
      imports: [runtime.GlowTourNextTrigger],
      template: "<glow-tour-next-trigger />",
    })
    class OutsideRootHarness {}

    document.body.append(document.createElement("angular-outside-root"));
    const reportError = console.error;
    console.error = () => {};
    try {
      await assert.rejects(
        () => bootstrapApplication(OutsideRootHarness),
        /inside <glow-tour-root/i,
      );
    } finally {
      console.error = reportError;
    }
  });

  test("reports Angular's required tour input error for an unbound root", async () => {
    @Component({
      selector: "angular-missing-tour",
      standalone: true,
      imports: [runtime.GlowTourRoot],
      template: "<glow-tour-root />",
    })
    class MissingTourHarness {}

    const errors: unknown[] = [];
    document.body.append(document.createElement("angular-missing-tour"));
    const app = await bootstrapApplication(MissingTourHarness, {
      providers: [
        {
          provide: ErrorHandler,
          useValue: { handleError: (error: unknown) => errors.push(error) },
        },
      ],
    });
    await settle();

    assert.equal(errors.length, 1);
    assert.match(String(errors[0]), /requires a tour input/i);
    await app.destroy();
  });

  test("passes the shared adapter acceptance contract", async () => {
    const primaryTour = runtime.createGlowTour();
    const secondaryTour = runtime.createGlowTour();
    const primaryTarget = document.createElement("button");
    const secondaryTarget = document.createElement("button");
    document.body.append(primaryTarget, secondaryTarget);

    @Component({
      selector: "angular-adapter-acceptance",
      standalone: true,
      imports: [
        runtime.GlowTourRoot,
        runtime.GlowTourPopover,
        runtime.GlowTourHeader,
        runtime.GlowTourContent,
        runtime.GlowTourNextTrigger,
      ],
      template: `
        <glow-tour-root [tour]="primaryTour" idPrefix="angular-acceptance-primary">
          <glow-tour-popover>
            <glow-tour-header />
            <glow-tour-content />
            <glow-tour-next-trigger />
          </glow-tour-popover>
        </glow-tour-root>
        <glow-tour-root [tour]="secondaryTour" idPrefix="angular-acceptance-secondary">
          <glow-tour-popover>
            <glow-tour-header />
            <glow-tour-content />
            <glow-tour-next-trigger />
          </glow-tour-popover>
        </glow-tour-root>
      `,
    })
    class AdapterAcceptanceHarness {
      readonly primaryTour = primaryTour;
      readonly secondaryTour = secondaryTour;
    }

    document.body.append(document.createElement("angular-adapter-acceptance"));
    const app = await bootstrapApplication(AdapterAcceptanceHarness);
    await settle();
    app.tick();

    const roots = Array.from(document.querySelectorAll<HTMLElement>("[data-glow-tour-root]"));
    assert.equal(roots.length, 2);
    const [primaryRoot, secondaryRoot] = roots;
    assert.ok(primaryRoot);
    assert.ok(secondaryRoot);

    await runAdapterAcceptance({
      content: (value) => value,
      name: "angular",
      primaryRoot,
      primaryTarget,
      primaryTour,
      secondaryRoot,
      secondaryTarget,
      secondaryTour,
      mountDuplicatePrimary: async () => {
        const errors: unknown[] = [];
        const host = document.createElement("angular-adapter-duplicate-primary");
        let duplicateApp: Awaited<ReturnType<typeof bootstrapApplication>> | undefined;
        let failure: unknown;

        @Component({
          selector: "angular-adapter-duplicate-primary",
          standalone: true,
          imports: [runtime.GlowTourRoot],
          template:
            '<glow-tour-root [tour]="tour" idPrefix="angular-acceptance-duplicate-primary" />',
        })
        class DuplicatePrimaryHarness {
          readonly tour = primaryTour;
        }

        document.body.append(host);
        try {
          duplicateApp = await bootstrapApplication(DuplicatePrimaryHarness, {
            providers: [
              {
                provide: ErrorHandler,
                useValue: { handleError: (error: unknown) => errors.push(error) },
              },
            ],
          });
          await settle();
          duplicateApp.tick();
          failure = errors[0];
        } catch (error) {
          failure = error;
        } finally {
          try {
            duplicateApp?.destroy();
          } catch (error) {
            if (failure === undefined) failure = error;
          }
          host.remove();
        }

        if (failure !== undefined) throw failure;
        throw new Error("Duplicate Angular root unexpectedly mounted.");
      },
      settle: async () => {
        await settle();
        app.tick();
        await settle();
      },
      unmount: async () => {
        app.destroy();
      },
    });
  });
});

// packages/react/src/react.browser.ts
import { afterEach, beforeEach, describe, test } from "bun:test";
import assert from "node:assert/strict";
import { Window } from "happy-dom";
import { runAdapterAcceptance } from "../../../scripts/adapter-acceptance";

let window: Window;

beforeEach(() => {
  window = new Window();
  Object.assign(globalThis, {
    Event: window.Event,
    Element: window.Element,
    HTMLElement: window.HTMLElement,
    KeyboardEvent: window.KeyboardEvent,
    MouseEvent: window.MouseEvent,
    MutationObserver: window.MutationObserver,
    Node: window.Node,
    cancelAnimationFrame: window.cancelAnimationFrame.bind(window),
    requestAnimationFrame: window.requestAnimationFrame.bind(window),
    ResizeObserver: window.ResizeObserver,
    SVGSVGElement: window.SVGSVGElement,
    cancelAnimationFrame: window.cancelAnimationFrame.bind(window),
    document: window.document,
    requestAnimationFrame: window.requestAnimationFrame.bind(window),
    window,
  });
  Reflect.set(globalThis, "IS_REACT_ACT_ENVIRONMENT", true);
});

afterEach(() => {
  window.close();
});

describe("react adapter browser behavior", () => {
  test("exposes reactive tour state to descendants", async () => {
    const [React, { createRoot }, { createGlowTour, GlowTour, useTour }] = await Promise.all([
      import("react"),
      import("react-dom/client"),
      import("./index"),
    ]);
    const container = document.createElement("div");
    const target = document.createElement("button");
    document.body.append(container, target);
    const tour = createGlowTour();
    const workflow = tour
      .create("reactive state")
      .step({ content: "First", target, title: "First" })
      .step({ content: "Second", target, title: "Second" })
      .finish();
    function Observer() {
      const state = useTour();
      return React.createElement("output", null, `${state.status}:${state.currentStepIndex}`);
    }
    const root = createRoot(container);
    await React.act(async () => {
      root.render(React.createElement(GlowTour.Root, { tour }, React.createElement(Observer)));
    });
    await React.act(async () => {
      await tour.run(workflow);
    });
    assert.equal(container.querySelector("output")?.textContent, "active:0");
    await React.act(async () => tour.advance());
    assert.equal(container.querySelector("output")?.textContent, "active:1");
    await React.act(async () => root.unmount());
  });

  test("keeps nested tour controls isolated from the outer root", async () => {
    const [React, { createRoot }, { createGlowTour, GlowTour }] = await Promise.all([
      import("react"),
      import("react-dom/client"),
      import("./index"),
    ]);
    const container = document.createElement("div");
    const outerTarget = document.createElement("button");
    const innerTarget = document.createElement("button");
    document.body.append(container, outerTarget, innerTarget);
    const outer = createGlowTour();
    const inner = createGlowTour();
    const workflow = (tour: typeof outer, target: HTMLElement, name: string) =>
      tour
        .create(name)
        .step({ content: "First", target, title: "First" })
        .step({ content: "Second", target, title: "Second" })
        .build();
    const root = createRoot(container);
    await React.act(async () => {
      root.render(
        React.createElement(
          GlowTour.Root,
          { idPrefix: "outer", tour: outer },
          React.createElement(GlowTour.NextTrigger),
          React.createElement(
            GlowTour.Root,
            { idPrefix: "inner", tour: inner },
            React.createElement(GlowTour.Popover),
            React.createElement(GlowTour.NextTrigger),
          ),
        ),
      );
    });
    await React.act(async () => {
      await outer.run(workflow(outer, outerTarget, "outer"));
      await inner.run(workflow(inner, innerTarget, "inner"));
    });
    const [outerNext, innerNext] = Array.from(
      container.querySelectorAll<HTMLButtonElement>("[data-glow-tour-next-trigger]"),
    );
    const outerDisabled = outerNext?.disabled;
    const outerAriaDisabled = outerNext?.getAttribute("aria-disabled");
    await React.act(async () => {
      innerNext?.dispatchEvent(new MouseEvent("click", { bubbles: true, cancelable: true }));
      await new Promise((resolve) => window.setTimeout(resolve, 0));
    });
    assert.equal(inner.state.get().currentStepIndex, 1);
    assert.equal(outer.state.get().currentStepIndex, 0);
    assert.equal(outerNext?.disabled, outerDisabled);
    assert.equal(outerNext?.getAttribute("aria-disabled"), outerAriaDisabled);
    await React.act(async () => root.unmount());
  });

  test("uses controller keyboard permission despite consumer-disabled next trigger order", async () => {
    const [React, { createRoot }, { createGlowTour, GlowTour }] = await Promise.all([
      import("react"),
      import("react-dom/client"),
      import("./index"),
    ]);
    const container = document.createElement("div");
    const target = document.createElement("button");
    document.body.append(container, target);
    const tour = createGlowTour();
    const workflow = tour
      .create("keyboard order")
      .step({ content: "First", target, title: "First" })
      .step({ content: "Second", target, title: "Second" })
      .step({ content: "Third", target, title: "Third" })
      .build();
    let setDisabledFirst!: (value: boolean) => void;
    function Harness() {
      const [disabledFirst, updateDisabledFirst] = React.useState(true);
      setDisabledFirst = updateDisabledFirst;
      const disabled = React.createElement(GlowTour.NextTrigger, { disabled: true });
      const enabled = React.createElement(GlowTour.NextTrigger);
      return React.createElement(
        GlowTour.Root,
        { tour },
        disabledFirst ? disabled : enabled,
        disabledFirst ? enabled : disabled,
      );
    }
    const root = createRoot(container);
    await React.act(async () => root.render(React.createElement(Harness)));
    await React.act(async () => {
      await tour.run(workflow);
    });
    const disabled = container.querySelector<HTMLButtonElement>(
      "[data-glow-tour-consumer-disabled]",
    );
    await React.act(async () => {
      disabled?.click();
      await new Promise((resolve) => window.setTimeout(resolve, 0));
    });
    assert.equal(tour.state.get().currentStepIndex, 0);
    await React.act(async () => {
      window.dispatchEvent(new window.KeyboardEvent("keydown", { key: "Enter" }));
      await new Promise((resolve) => window.setTimeout(resolve, 0));
    });
    assert.equal(tour.state.get().currentStepIndex, 1);
    await React.act(async () => {
      await tour.previous();
      setDisabledFirst(false);
    });
    await React.act(async () => {
      window.dispatchEvent(new window.KeyboardEvent("keydown", { key: "Enter" }));
      await new Promise((resolve) => window.setTimeout(resolve, 0));
    });
    assert.equal(tour.state.get().currentStepIndex, 1);
    await React.act(async () => root.unmount());
  });

  test("synchronizes custom keyboard shortcuts on a late next trigger", async () => {
    const [React, { createRoot }, { createGlowTour, GlowTour }] = await Promise.all([
      import("react"),
      import("react-dom/client"),
      import("./index"),
    ]);
    const container = document.createElement("div");
    const target = document.createElement("button");
    document.body.append(container, target);
    const tour = createGlowTour();
    const workflow = tour
      .create("custom shortcuts")
      .step({
        content: "First",
        popover: { keyboardShortcuts: { next: ["N"] } },
        target,
        title: "First",
      })
      .step({ content: "Second", target, title: "Second" })
      .build();
    let show!: () => void;
    function Harness() {
      const [visible, setVisible] = React.useState(false);
      show = () => setVisible(true);
      return React.createElement(
        GlowTour.Root,
        { tour },
        visible ? React.createElement(GlowTour.NextTrigger) : null,
      );
    }
    const root = createRoot(container);
    await React.act(async () => root.render(React.createElement(Harness)));
    await React.act(async () => {
      await tour.run(workflow);
      show();
    });
    await new Promise((resolve) => window.setTimeout(resolve, 0));
    const next = container.querySelector<HTMLButtonElement>("[data-glow-tour-next-trigger]");
    assert.equal(next?.getAttribute("aria-keyshortcuts"), "N");
    await React.act(async () => root.unmount());
  });

  test("delegates commands to controls that appear while a tour is active", async () => {
    const [React, { createRoot }, { createGlowTour, GlowTour }] = await Promise.all([
      import("react"),
      import("react-dom/client"),
      import("./index"),
    ]);
    const container = document.createElement("div");
    const target = document.createElement("button");
    document.body.append(container, target);
    const tour = createGlowTour();
    const workflow = tour
      .create("dynamic controls")
      .step({ content: "First", target, title: "First" })
      .step({ content: "Second", target, title: "Second" })
      .build();
    let setShowNext!: (show: boolean) => void;

    function Harness() {
      const [showNext, updateShowNext] = React.useState(false);
      setShowNext = updateShowNext;
      return React.createElement(
        GlowTour.Root,
        { tour },
        React.createElement(GlowTour.CancelTrigger),
        React.createElement(GlowTour.BackTrigger),
        showNext ? React.createElement(GlowTour.NextTrigger) : null,
      );
    }

    const root = createRoot(container);
    await React.act(async () => {
      root.render(React.createElement(Harness));
    });
    await React.act(async () => {
      await tour.run(workflow);
    });
    const firstBack = container.querySelector<HTMLButtonElement>("[data-glow-tour-back-trigger]");
    assert.equal(firstBack?.disabled, true);
    assert.equal(firstBack?.getAttribute("aria-disabled"), "true");
    const cancel = container.querySelector<HTMLButtonElement>("[data-glow-tour-cancel-trigger]");
    assert.equal(cancel?.disabled, false);
    await React.act(async () => {
      cancel?.dispatchEvent(new MouseEvent("click", { bubbles: true, cancelable: true }));
      await Promise.resolve();
    });
    assert.equal(tour.state.get().status, "cancelled");

    await React.act(async () => {
      await tour.run(workflow);
      await tour.advance();
    });
    await new Promise((resolve) => window.setTimeout(resolve, 0));
    const back = container.querySelector<HTMLButtonElement>("[data-glow-tour-back-trigger]");
    assert.equal(back?.disabled, false);
    assert.equal(back?.getAttribute("aria-keyshortcuts"), "ArrowLeft Backspace");
    await React.act(async () => {
      back?.dispatchEvent(new MouseEvent("click", { bubbles: true, cancelable: true }));
      await Promise.resolve();
    });
    assert.equal(tour.state.get().currentStepIndex, 0);

    await React.act(async () => setShowNext(true));
    await new Promise((resolve) => window.setTimeout(resolve, 0));
    const next = container.querySelector<HTMLButtonElement>("[data-glow-tour-next-trigger]");
    assert.equal(next?.disabled, false);
    assert.equal(next?.getAttribute("aria-keyshortcuts"), "Enter ArrowRight");
    await React.act(async () => {
      next?.dispatchEvent(new MouseEvent("click", { bubbles: true, cancelable: true }));
      await Promise.resolve();
    });
    assert.equal(tour.state.get().currentStepIndex, 1);

    await React.act(async () => root.unmount());
  });

  test("composes custom child and wrapper click handlers before navigation", async () => {
    const [React, { createRoot }, { createGlowTour, GlowTour }] = await Promise.all([
      import("react"),
      import("react-dom/client"),
      import("./index"),
    ]);
    const container = document.createElement("div");
    const target = document.createElement("button");
    document.body.append(container, target);
    const tour = createGlowTour();
    const workflow = tour
      .create("composed handlers")
      .step({ content: "First", target, title: "First" })
      .step({ content: "Second", target, title: "Second" })
      .build();
    let childClicks = 0;
    let wrapperClicks = 0;
    const root = createRoot(container);

    await React.act(async () => {
      root.render(
        React.createElement(
          GlowTour.Root,
          { tour },
          React.createElement(
            GlowTour.NextTrigger,
            { onClick: () => (wrapperClicks += 1) },
            React.createElement("button", { onClick: () => (childClicks += 1) }),
          ),
        ),
      );
    });
    await React.act(async () => {
      await tour.run(workflow);
    });
    const next = container.querySelector<HTMLButtonElement>("[data-glow-tour-next-trigger]");
    await React.act(async () => {
      next?.dispatchEvent(new MouseEvent("click", { bubbles: true, cancelable: true }));
      await Promise.resolve();
    });
    assert.equal(childClicks, 1);
    assert.equal(wrapperClicks, 1);
    assert.equal(tour.state.get().currentStepIndex, 1);

    await React.act(async () => root.unmount());
  });

  test("lets a consumer prevent a delegated next click without navigation", async () => {
    const [React, { createRoot }, { createGlowTour, GlowTour }] = await Promise.all([
      import("react"),
      import("react-dom/client"),
      import("./index"),
    ]);
    const container = document.createElement("div");
    const target = document.createElement("button");
    document.body.append(container, target);
    const tour = createGlowTour();
    const workflow = tour
      .create("prevented")
      .step({ content: "First", target, title: "First" })
      .step({ content: "Second", target, title: "Second" })
      .build();
    const root = createRoot(container);

    await React.act(async () => {
      root.render(
        React.createElement(
          GlowTour.Root,
          { tour },
          React.createElement(GlowTour.NextTrigger, { onClick: (event) => event.preventDefault() }),
        ),
      );
    });
    await React.act(async () => {
      await tour.run(workflow);
    });
    const next = container.querySelector<HTMLButtonElement>("[data-glow-tour-next-trigger]");
    next?.dispatchEvent(new MouseEvent("click", { bubbles: true, cancelable: true }));
    await new Promise((resolve) => window.setTimeout(resolve, 0));
    assert.equal(tour.state.get().currentStepIndex, 0);

    await React.act(async () => root.unmount());
  });

  test("advances exactly once when a consumer does not prevent a delegated next click", async () => {
    const [React, { createRoot }, { createGlowTour, GlowTour }] = await Promise.all([
      import("react"),
      import("react-dom/client"),
      import("./index"),
    ]);
    const container = document.createElement("div");
    const target = document.createElement("button");
    document.body.append(container, target);
    const tour = createGlowTour();
    let advances = 0;
    const workflow = tour
      .create("nonpreventing")
      .step({ content: "First", target, title: "First" })
      .beforeAdvance(() => {
        advances += 1;
      })
      .step({ content: "Second", target, title: "Second" })
      .build();
    const root = createRoot(container);

    await React.act(async () => {
      root.render(
        React.createElement(GlowTour.Root, { tour }, React.createElement(GlowTour.NextTrigger)),
      );
    });
    await React.act(async () => {
      await tour.run(workflow);
    });
    const next = container.querySelector<HTMLButtonElement>("[data-glow-tour-next-trigger]");
    await React.act(async () => {
      next?.dispatchEvent(new MouseEvent("click", { bubbles: true, cancelable: true }));
      await new Promise((resolve) => window.setTimeout(resolve, 0));
    });
    assert.equal(tour.state.get().currentStepIndex, 1);
    assert.equal(advances, 1);

    await React.act(async () => root.unmount());
  });

  test("defers a next click and abandons it after the consumer replaces the workflow", async () => {
    const [React, { createRoot }, { createGlowTour, GlowTour }] = await Promise.all([
      import("react"),
      import("react-dom/client"),
      import("./index"),
    ]);
    const container = document.createElement("div");
    const target = document.createElement("button");
    document.body.append(container, target);
    const tour = createGlowTour();
    const first = tour
      .create("first")
      .step({ content: "First", target, title: "First" })
      .step({ content: "Second", target, title: "Second" })
      .build();
    const replacement = tour
      .create("replacement")
      .step({ content: "Replacement", target, title: "Replacement" })
      .step({ content: "Replacement next", target, title: "Replacement next" })
      .build();
    const root = createRoot(container);

    await React.act(async () => {
      root.render(
        React.createElement(
          GlowTour.Root,
          { tour },
          React.createElement(GlowTour.NextTrigger, { onClick: () => tour.run(replacement) }),
        ),
      );
    });
    await React.act(async () => {
      await tour.run(first);
    });
    const next = container.querySelector<HTMLButtonElement>("[data-glow-tour-next-trigger]");
    await React.act(async () => {
      next?.dispatchEvent(new MouseEvent("click", { bubbles: true, cancelable: true }));
      await new Promise((resolve) => window.setTimeout(resolve, 0));
    });
    assert.equal(tour.state.get().currentStep?.currentProps.content, "Replacement");
    assert.equal(tour.state.get().currentStepIndex, 0);

    await React.act(async () => root.unmount());
  });

  test("keeps native disabled, consumer marker, and aria-disabled coherent when disabled toggles", async () => {
    const [React, { createRoot }, { createGlowTour, GlowTour }] = await Promise.all([
      import("react"),
      import("react-dom/client"),
      import("./index"),
    ]);
    const container = document.createElement("div");
    const target = document.createElement("button");
    document.body.append(container, target);
    const tour = createGlowTour();
    const workflow = tour
      .create("toggle disabled")
      .step({ content: "First", target, title: "First" })
      .step({ content: "Second", target, title: "Second" })
      .build();
    let setDisabled!: (disabled: boolean) => void;

    function Harness() {
      const [disabled, updateDisabled] = React.useState(true);
      setDisabled = updateDisabled;
      return React.createElement(
        GlowTour.Root,
        { tour },
        React.createElement(GlowTour.NextTrigger, { disabled }),
      );
    }

    const root = createRoot(container);
    await React.act(async () => {
      root.render(React.createElement(Harness));
    });
    await React.act(async () => {
      await tour.run(workflow);
    });
    const next = container.querySelector<HTMLButtonElement>("[data-glow-tour-next-trigger]");
    assert.equal(next?.disabled, true);
    assert.equal(next?.getAttribute("data-glow-tour-consumer-disabled"), "true");
    assert.equal(next?.getAttribute("aria-disabled"), "true");

    await React.act(async () => setDisabled(false));
    assert.equal(next?.disabled, false);
    assert.equal(next?.hasAttribute("data-glow-tour-consumer-disabled"), false);
    assert.equal(next?.getAttribute("aria-disabled"), "false");
    await React.act(async () => {
      next?.click();
      await new Promise((resolve) => window.setTimeout(resolve, 0));
    });
    assert.equal(tour.state.get().currentStepIndex, 1);

    await React.act(async () => root.unmount());
  });

  test("treats a custom child button's disabled prop as consumer disabled", async () => {
    const [React, { createRoot }, { createGlowTour, GlowTour }] = await Promise.all([
      import("react"),
      import("react-dom/client"),
      import("./index"),
    ]);
    const container = document.createElement("div");
    const target = document.createElement("button");
    document.body.append(container, target);
    const tour = createGlowTour();
    const workflow = tour
      .create("child disabled")
      .step({ content: "First", target, title: "First" })
      .step({ content: "Second", target, title: "Second" })
      .build();
    const root = createRoot(container);

    await React.act(async () => {
      root.render(
        React.createElement(
          GlowTour.Root,
          { tour },
          React.createElement(
            GlowTour.NextTrigger,
            null,
            React.createElement("button", {
              disabled: true,
              onClick: (event) => event.preventDefault(),
            }),
          ),
        ),
      );
    });
    await React.act(async () => {
      await tour.run(workflow);
    });
    const next = container.querySelector<HTMLButtonElement>("[data-glow-tour-next-trigger]");
    assert.equal(next?.disabled, true);
    assert.equal(next?.getAttribute("data-glow-tour-consumer-disabled"), "true");
    assert.equal(next?.getAttribute("aria-disabled"), "true");
    next?.click();
    await new Promise((resolve) => window.setTimeout(resolve, 0));
    assert.equal(tour.state.get().currentStepIndex, 0);

    await React.act(async () => root.unmount());
  });

  test("keeps consumer-disabled next triggers disabled after the tour becomes active", async () => {
    const [React, { createRoot }, { createGlowTour, GlowTour }] = await Promise.all([
      import("react"),
      import("react-dom/client"),
      import("./index"),
    ]);
    const container = document.createElement("div");
    document.body.append(container);
    const target = document.createElement("button");
    document.body.append(target);
    const tour = createGlowTour();
    const workflow = tour
      .create("consumer disabled")
      .step({ content: "First", target, title: "First" })
      .step({ content: "Second", target, title: "Second" })
      .build();
    const root = createRoot(container);

    await React.act(async () => {
      root.render(
        React.createElement(
          React.StrictMode,
          null,
          React.createElement(
            GlowTour.Root,
            { tour },
            React.createElement(
              React.Fragment,
              null,
              React.createElement(GlowTour.Popover, null),
              React.createElement(GlowTour.Header, null),
              React.createElement(GlowTour.Content, null),
              React.createElement(GlowTour.NextTrigger, {
                disabled: true,
                finishLabel: "Complete",
                nextLabel: "Continue",
              }),
            ),
          ),
        ),
      );
    });
    const rootElement = container.querySelector<HTMLElement>("[data-glow-tour-root]");
    const popover = container.querySelector<HTMLElement>("[data-glow-tour-popover]");
    const header = container.querySelector<HTMLElement>("[data-glow-tour-header]");
    const content = container.querySelector<HTMLElement>("[data-glow-tour-content]");
    const next = container.querySelector<HTMLButtonElement>("[data-glow-tour-next-trigger]");

    assert.equal(rootElement?.id, "glow-tour-root");
    assert.equal(popover?.getAttribute("aria-labelledby"), header?.id);
    assert.equal(popover?.getAttribute("aria-describedby"), content?.id);
    assert.equal(next?.getAttribute("aria-controls"), popover?.id);
    assert.equal(next?.disabled, true);
    await React.act(async () => {
      await tour.run(workflow);
    });
    assert.equal(next?.disabled, true);
    assert.equal(next?.textContent, "Continue");
    next?.click();
    await new Promise((resolve) => window.setTimeout(resolve, 10));
    assert.equal(tour.state.get().currentStepIndex, 0);
    await React.act(async () => {
      await tour.advance();
    });
    assert.equal(next?.textContent, "Complete");

    await React.act(async () => {
      root.unmount();
    });
    assert.equal(rootElement?.id, "");
  });

  test("replaces the root tour and renders the replacement snapshot", async () => {
    const [React, { createRoot }, { createGlowTour, GlowTour }] = await Promise.all([
      import("react"),
      import("react-dom/client"),
      import("./index"),
    ]);
    const container = document.createElement("div");
    document.body.append(container);
    const target = document.createElement("button");
    document.body.append(target);
    const first = createGlowTour();
    const second = createGlowTour();
    const firstWorkflow = first
      .create("first")
      .step({ content: "First tour", target, title: "First" })
      .build();
    const secondWorkflow = second
      .create("second")
      .step({ content: "Second tour", target, title: "Second" })
      .build();
    let replaceTour!: (tour: typeof second) => void;

    function Harness() {
      const [tour, setTour] = React.useState(first);
      replaceTour = setTour;
      return React.createElement(
        GlowTour.Root,
        { tour },
        React.createElement(GlowTour.Content, null),
      );
    }

    const root = createRoot(container);
    await React.act(async () => {
      root.render(React.createElement(Harness));
    });
    await React.act(async () => {
      await first.run(firstWorkflow);
    });
    assert.equal(container.textContent, "First tour");

    await React.act(async () => {
      replaceTour(second);
    });
    await React.act(async () => {
      await second.run(secondWorkflow);
    });
    assert.equal(container.textContent, "Second tour");

    await React.act(async () => {
      root.unmount();
    });
  });

  test("passes the shared adapter acceptance contract with sibling roots", async () => {
    const [React, { createRoot }, { createGlowTour, GlowTour }] = await Promise.all([
      import("react"),
      import("react-dom/client"),
      import("./index"),
    ]);
    const container = document.createElement("div");
    const primaryTarget = document.createElement("button");
    const secondaryTarget = document.createElement("button");
    document.body.append(container, primaryTarget, secondaryTarget);
    const primaryTour = createGlowTour();
    const secondaryTour = createGlowTour();
    const root = createRoot(container);
    const actTour = (tour: typeof primaryTour) => ({
      async advance() {
        await React.act(() => tour.advance());
      },
      async cancel() {
        await React.act(() => tour.cancel());
      },
      create: tour.create.bind(tour),
      dispose() {
        React.act(() => tour.dispose());
      },
      async goToStep(index: number) {
        await React.act(() => tour.goToStep(index));
      },
      async previous() {
        await React.act(() => tour.previous());
      },
      async run(workflow: Parameters<typeof tour.run>[0]) {
        await React.act(() => tour.run(workflow));
      },
      state: tour.state,
      updateCurrentStep(update: Parameters<typeof tour.updateCurrentStep>[0]) {
        React.act(() => tour.updateCurrentStep(update));
      },
    });

    await React.act(async () => {
      root.render(
        React.createElement(
          React.Fragment,
          null,
          React.createElement(
            GlowTour.Root,
            { idPrefix: "react-primary", tour: primaryTour },
            React.createElement(GlowTour.Popover),
            React.createElement(GlowTour.Header),
            React.createElement(GlowTour.Content),
            React.createElement(GlowTour.NextTrigger),
          ),
          React.createElement(
            GlowTour.Root,
            { idPrefix: "react-secondary", tour: secondaryTour },
            React.createElement(GlowTour.Popover),
            React.createElement(GlowTour.Header),
            React.createElement(GlowTour.Content),
            React.createElement(GlowTour.NextTrigger),
          ),
        ),
      );
    });
    const [primaryRoot, secondaryRoot] = Array.from(
      container.querySelectorAll<HTMLElement>("[data-glow-tour-root]"),
    );
    assert.ok(primaryRoot);
    assert.ok(secondaryRoot);

    await runAdapterAcceptance({
      content(value) {
        return value;
      },
      name: "react",
      async mountDuplicatePrimary() {
        const duplicateContainer = document.createElement("div");
        document.body.append(duplicateContainer);
        const duplicateRoot = createRoot(duplicateContainer);
        let mountError: unknown;
        try {
          await React.act(async () => {
            duplicateRoot.render(
              React.createElement(
                GlowTour.Root,
                { idPrefix: "react-duplicate", tour: primaryTour },
                React.createElement(GlowTour.Popover),
                React.createElement(GlowTour.Header),
                React.createElement(GlowTour.Content),
                React.createElement(GlowTour.NextTrigger),
              ),
            );
          });
        } catch (error) {
          mountError = error;
        }
        let cleanupError: unknown;
        try {
          await React.act(async () => duplicateRoot.unmount());
        } catch (error) {
          cleanupError = error;
        }
        duplicateContainer.remove();
        if (mountError) throw mountError;
        if (cleanupError) throw cleanupError;
      },
      primaryRoot,
      primaryTarget,
      primaryTour: actTour(primaryTour),
      secondaryRoot,
      secondaryTarget,
      secondaryTour: actTour(secondaryTour),
      async settle() {
        await React.act(async () => {
          await new Promise((resolve) => window.setTimeout(resolve, 0));
        });
      },
      async unmount() {
        await React.act(async () => root.unmount());
        container.remove();
        primaryTarget.remove();
        secondaryTarget.remove();
      },
    });
  });
});
