// packages/solid/src/components/tour-components.ts
import type { GlowTour as CoreGlowTour, TourState } from "@glowhop/core-tour";
import {
  createComponent,
  createContext,
  createEffect,
  createSignal,
  type JSX,
  mergeProps,
  onCleanup,
  type ParentProps,
  Show,
  splitProps,
  useContext,
  type ValidComponent,
} from "solid-js";
import { Dynamic } from "solid-js/web";
import { getAdapterBridge, type RootBinding, solidAdapter } from "../adapter-bridge";
import type { SolidTourContent } from "../glow-tour";

type Tour = CoreGlowTour<SolidTourContent>;
type RootProps = ParentProps<
  Omit<JSX.HTMLAttributes<HTMLDivElement>, "id" | "ref"> & {
    idPrefix?: string;
    tour: Tour;
  }
>;
type ElementProps = ParentProps<
  Omit<JSX.HTMLAttributes<HTMLElement>, "id" | "ref"> & { as?: ValidComponent }
>;
type ContentProps = Omit<JSX.HTMLAttributes<HTMLElement>, "children" | "id">;
type OverlayProps = ParentProps<Omit<JSX.SvgSVGAttributes<SVGSVGElement>, "ref">>;
type PointerProps = ParentProps<
  Omit<JSX.HTMLAttributes<HTMLElement>, "aria-hidden" | "ref"> & { as?: ValidComponent }
>;
type ButtonProps = Omit<JSX.ButtonHTMLAttributes<HTMLButtonElement>, "children" | "type"> & {
  children?: (props: JSX.ButtonHTMLAttributes<HTMLButtonElement>) => JSX.Element;
  disabled?: boolean;
};
type BackTriggerProps = ButtonProps & { backLabel?: string };
type NextTriggerProps = ButtonProps & { finishLabel?: string; nextLabel?: string };
type CancelTriggerProps = ButtonProps & { cancelLabel?: string };
type ButtonClickEvent = MouseEvent & { currentTarget: HTMLButtonElement; target: Element };

interface TourContextValue {
  readonly binding: () => RootBinding | null;
  readonly tour: () => Tour;
}

const TourContext = createContext<TourContextValue>();

function useTourContext() {
  const context = useContext(TourContext);
  if (!context) {
    throw new Error("GlowTour components must be rendered inside <GlowTour.Root tour={...}>.");
  }
  return context;
}

function useTourSnapshot(tour: () => Tour) {
  const [snapshot, setSnapshot] = createSignal<TourState<SolidTourContent>>(tour().state.get());
  createEffect(() => {
    const activeTour = tour();
    setSnapshot(activeTour.state.get());
    const unsubscribe = activeTour.state.subscribe(setSnapshot);
    onCleanup(unsubscribe);
  });
  return snapshot;
}

function useBoundElement<T extends Element>(
  bind: (binding: RootBinding, element: T) => () => void,
) {
  const context = useTourContext();
  const [element, setElement] = createSignal<T | null>(null);
  createEffect(() => {
    const activeBinding = context.binding();
    const activeElement = element();
    if (!activeBinding || !activeElement) return;
    return bind(activeBinding, activeElement);
  });
  return setElement;
}

function currentStep(snapshot: TourState<SolidTourContent>) {
  return snapshot.currentStep?.currentProps ?? null;
}

export function Root(props: RootProps): JSX.Element {
  const [local, other] = splitProps(props, ["children", "idPrefix", "tour"]);
  const [element, setElement] = createSignal<HTMLElement | null>(null);
  const [binding, setBinding] = createSignal<RootBinding | null>(null);

  createEffect(() => {
    const root = element();
    const tour = local.tour;
    const idPrefix = local.idPrefix;
    if (!root) return;
    const lease = getAdapterBridge(tour).connectRoot({
      adapter: solidAdapter,
      idPrefix,
      root,
    });
    setBinding(lease);
    onCleanup(() => {
      lease.release();
      setBinding((active) => (active === lease ? null : active));
    });
  });

  return createComponent(TourContext.Provider, {
    value: {
      binding,
      tour() {
        return local.tour;
      },
    },
    get children() {
      return createComponent(
        Dynamic,
        mergeProps(other, {
          component: "div",
          "data-glow-tour-root": "",
          ref: setElement,
          get children() {
            return local.children;
          },
        }),
      );
    },
  });
}

export function Popover(props: ElementProps): JSX.Element {
  const context = useTourContext();
  const [local, other] = splitProps(props, ["as", "children"]);
  const ref = useBoundElement<HTMLElement>((binding, element) => binding.bindPopover(element));

  return createComponent(
    Dynamic,
    mergeProps(other, {
      get "aria-describedby"() {
        return context.binding()?.ids.description;
      },
      get "aria-labelledby"() {
        return context.binding()?.ids.title;
      },
      get component() {
        return local.as ?? "section";
      },
      "data-glow-tour-popover": "",
      get id() {
        return context.binding()?.ids.popover;
      },
      ref,
      role: "dialog",
      tabIndex: -1,
      get children() {
        return local.children;
      },
    }),
  );
}

export function Header(props: ContentProps): JSX.Element {
  const context = useTourContext();
  const snapshot = useTourSnapshot(context.tour);
  return createComponent(
    Dynamic,
    mergeProps(props, {
      component: "header",
      "data-glow-tour-header": "",
      get id() {
        return context.binding()?.ids.title;
      },
      get children() {
        return currentStep(snapshot())?.title ?? null;
      },
    }),
  );
}

export function Content(props: ContentProps): JSX.Element {
  const context = useTourContext();
  const snapshot = useTourSnapshot(context.tour);
  return createComponent(
    Dynamic,
    mergeProps(props, {
      "aria-live": "polite",
      component: "div",
      "data-glow-tour-content": "",
      get id() {
        return context.binding()?.ids.description;
      },
      get children() {
        return currentStep(snapshot())?.content ?? null;
      },
    }),
  );
}

export function Footer(props: ElementProps): JSX.Element {
  const context = useTourContext();
  const snapshot = useTourSnapshot(context.tour);
  return Show({
    get when() {
      return !currentStep(snapshot())?.hideFooter;
    },
    get children() {
      return createComponent(
        Dynamic,
        mergeProps(props, {
          component: "footer",
          "data-glow-tour-footer": "",
        }),
      );
    },
  });
}

export function Overlay(props: OverlayProps): JSX.Element {
  const [local, other] = splitProps(props, ["children", "viewBox"]);
  const ref = useBoundElement<SVGSVGElement>((binding, element) => binding.bindOverlay(element));
  const path = createComponent(Dynamic, {
    component: "path",
    "data-glow-tour-overlay-path": "",
    "fill-rule": "evenodd",
  });

  return createComponent(
    Dynamic,
    mergeProps(other, {
      "aria-hidden": true,
      component: "svg",
      "data-glow-tour-overlay": "",
      focusable: "false",
      ref,
      role: "presentation",
      get viewBox() {
        return local.viewBox ?? "0 0 0 0";
      },
      get children() {
        return [path, local.children];
      },
    }),
  );
}

export function Pointer(props: PointerProps): JSX.Element {
  const [local, other] = splitProps(props, ["as", "children"]);
  const ref = useBoundElement<HTMLElement>((binding, element) => binding.bindPointer(element));
  const content = createComponent(Dynamic, {
    component: "div",
    "data-glow-tour-pointer-content": "",
    get children() {
      return local.children;
    },
  });

  return createComponent(
    Dynamic,
    mergeProps(other, {
      "aria-hidden": "true",
      get component() {
        return local.as ?? "div";
      },
      "data-glow-tour-pointer": "",
      ref,
      children: content,
    }),
  );
}

function Trigger(
  props: ButtonProps & {
    capabilityDisabled: boolean;
    label: string;
    marker: "back" | "cancel" | "next";
  },
): JSX.Element {
  const context = useTourContext();
  const [local, other] = splitProps(props, ["children", "capabilityDisabled", "label", "marker"]);
  const buttonProps = mergeProps(other, {
    get "aria-controls"() {
      return context.binding()?.ids.popover;
    },
    get "aria-label"() {
      return other["aria-label"] || local.label;
    },
    get "aria-disabled"() {
      return local.capabilityDisabled || other.disabled === true;
    },
    get "data-glow-tour-back-trigger"() {
      return local.marker === "back" ? true : undefined;
    },
    get "data-glow-tour-cancel-trigger"() {
      return local.marker === "cancel" ? true : undefined;
    },
    get "data-glow-tour-consumer-disabled"() {
      return other.disabled === true ? "true" : undefined;
    },
    get "data-glow-tour-next-trigger"() {
      return local.marker === "next" ? true : undefined;
    },
    get disabled() {
      return local.capabilityDisabled || other.disabled === true;
    },
    onClick(event: ButtonClickEvent) {
      if (typeof other.onClick === "function") other.onClick(event);
    },
    type: "button" as const,
  });

  if (local.children) return local.children(buttonProps);
  return createComponent(
    Dynamic,
    mergeProps(buttonProps, {
      component: "button",
      get children() {
        return local.label;
      },
    }),
  );
}

export function BackTrigger(props: BackTriggerProps): JSX.Element {
  const context = useTourContext();
  const snapshot = useTourSnapshot(context.tour);
  return Show({
    get when() {
      const step = currentStep(snapshot());
      return !snapshot().isFirstStep && !step?.hideBackButton;
    },
    get children() {
      return Trigger(
        mergeProps(props, {
          get capabilityDisabled() {
            return !snapshot().canPrevious || currentStep(snapshot())?.disableBackButton === true;
          },
          label: props.backLabel ?? "Back step",
          marker: "back" as const,
        }),
      );
    },
  });
}

export function NextTrigger(props: NextTriggerProps): JSX.Element {
  const context = useTourContext();
  const snapshot = useTourSnapshot(context.tour);
  return Show({
    get when() {
      return !currentStep(snapshot())?.hideNextButton;
    },
    get children() {
      return Trigger(
        mergeProps(props, {
          get capabilityDisabled() {
            return !snapshot().canAdvance || currentStep(snapshot())?.disableNextButton === true;
          },
          get label() {
            return snapshot().isLastStep
              ? (props.finishLabel ?? "Finish tour")
              : (props.nextLabel ?? "Next step");
          },
          marker: "next" as const,
        }),
      );
    },
  });
}

export function CancelTrigger(props: CancelTriggerProps): JSX.Element {
  const context = useTourContext();
  const snapshot = useTourSnapshot(context.tour);
  return Show({
    get when() {
      return snapshot().canCancel;
    },
    get children() {
      return Trigger(
        mergeProps(props, {
          get capabilityDisabled() {
            return !snapshot().canCancel;
          },
          label: props.cancelLabel ?? "Cancel tour",
          marker: "cancel" as const,
        }),
      );
    },
  });
}

export const GlowTour = {
  Root,
  Popover,
  Header,
  Content,
  Footer,
  Overlay,
  Pointer,
  BackTrigger,
  NextTrigger,
  CancelTrigger,
};

// packages/react/src/components/tour-components.tsx
import type { GlowTour as CoreGlowTour, TourState } from "@glowhop/core-tour";
import * as React from "react";
import { getAdapterBridge, type RootBinding, reactAdapter } from "../adapter-bridge";
import type { ReactTourContent } from "../glow-tour";

type Tour = CoreGlowTour<ReactTourContent>;
type RootProps = Omit<React.HTMLAttributes<HTMLDivElement>, "children" | "id" | "ref"> & {
  children?: React.ReactNode;
  idPrefix?: string;
  tour: Tour;
};
type ElementProps = Omit<React.HTMLAttributes<HTMLElement>, "id" | "ref"> & {
  as?: React.ElementType;
};
type ContentProps = Omit<React.HTMLAttributes<HTMLElement>, "children" | "id">;
type OverlayProps = Omit<React.SVGAttributes<SVGSVGElement>, "ref">;
type PointerProps = Omit<React.HTMLAttributes<HTMLElement>, "aria-hidden" | "ref"> & {
  as?: React.ElementType;
};
type ButtonProps = Omit<React.ButtonHTMLAttributes<HTMLButtonElement>, "children" | "type"> & {
  children?:
    | React.ReactElement<React.ButtonHTMLAttributes<HTMLButtonElement>>
    | ((props: React.ButtonHTMLAttributes<HTMLButtonElement>) => React.ReactElement);
};
type BackTriggerProps = ButtonProps & { backLabel?: string };
type NextTriggerProps = ButtonProps & { finishLabel?: string; nextLabel?: string };
type CancelTriggerProps = ButtonProps;

interface TourContextValue {
  readonly binding: RootBinding | null;
  readonly tour: Tour;
}

const TourContext = React.createContext<TourContextValue | null>(null);

function useTourContext() {
  const context = React.useContext(TourContext);
  if (!context) {
    throw new Error("GlowTour components must be rendered inside <GlowTour.Root tour={...}>.");
  }
  return context;
}

function useTourSnapshot(tour: Tour): TourState<ReactTourContent> {
  return React.useSyncExternalStore(tour.state.subscribe, tour.state.get, tour.state.get);
}

function useBoundElement<T extends Element>(
  bind: (binding: RootBinding, element: T) => () => void,
) {
  const { binding } = useTourContext();
  const [element, setElement] = React.useState<T | null>(null);

  React.useEffect(() => {
    if (!binding || !element) return;
    return bind(binding, element);
  }, [bind, binding, element]);

  return setElement;
}

function useStep(snapshot: TourState<ReactTourContent>) {
  return snapshot.currentStep?.currentProps ?? null;
}

export function Root({ children, idPrefix, tour, ...props }: RootProps) {
  const mounted = React.useRef<{ binding: RootBinding; element: HTMLDivElement } | null>(null);
  const [binding, setBinding] = React.useState<RootBinding | null>(null);
  const release = React.useCallback(() => {
    const current = mounted.current;
    if (!current) return;
    mounted.current = null;
    current.binding.release();
    setBinding((active) => (active === current.binding ? null : active));
  }, []);
  const connect = React.useCallback(
    (element: HTMLDivElement | null) => {
      release();
      if (!element) return;
      const nextBinding = getAdapterBridge(tour).connectRoot({
        adapter: reactAdapter,
        idPrefix,
        root: element,
      });
      mounted.current = { binding: nextBinding, element };
      setBinding(nextBinding);
    },
    [idPrefix, release, tour],
  );
  const context = React.useMemo(() => ({ binding, tour }), [binding, tour]);

  return (
    <TourContext.Provider value={context}>
      <div {...props} data-glow-tour-root ref={connect}>
        {children}
      </div>
    </TourContext.Provider>
  );
}

export function Popover({ as: Component = "section", ...props }: ElementProps) {
  const { binding } = useTourContext();
  const ref = useBoundElement<HTMLElement>((activeBinding, element) =>
    activeBinding.bindPopover(element),
  );

  return (
    <Component
      {...props}
      aria-describedby={binding?.ids.description}
      aria-labelledby={binding?.ids.title}
      data-glow-tour-popover
      id={binding?.ids.popover}
      ref={ref}
      role="dialog"
      tabIndex={-1}
    />
  );
}

export function Header(props: ContentProps) {
  const { binding, tour } = useTourContext();
  const step = useStep(useTourSnapshot(tour));

  return (
    <header {...props} data-glow-tour-header id={binding?.ids.title}>
      {step?.title ?? null}
    </header>
  );
}

export function Content(props: ContentProps) {
  const { binding, tour } = useTourContext();
  const step = useStep(useTourSnapshot(tour));

  return (
    <div {...props} aria-live="polite" data-glow-tour-content id={binding?.ids.description}>
      {step?.content ?? null}
    </div>
  );
}

export function Footer({ children, ...props }: ElementProps) {
  const { tour } = useTourContext();
  const step = useStep(useTourSnapshot(tour));
  if (step?.hideFooter) return null;

  return (
    <footer {...props} data-glow-tour-footer>
      {children}
    </footer>
  );
}

export function Overlay({ children, viewBox = "0 0 0 0", ...props }: OverlayProps) {
  const ref = useBoundElement<SVGSVGElement>((binding, element) => binding.bindOverlay(element));

  return (
    <svg
      {...props}
      aria-hidden
      data-glow-tour-overlay
      focusable="false"
      ref={ref}
      role="presentation"
      viewBox={viewBox}
    >
      <path data-glow-tour-overlay-path fillRule="evenodd" />
      {children}
    </svg>
  );
}

export function Pointer({ as: Component = "div", children, ...props }: PointerProps) {
  const ref = useBoundElement<HTMLElement>((binding, element) => binding.bindPointer(element));

  return (
    <Component {...props} aria-hidden="true" data-glow-tour-pointer ref={ref}>
      <div data-glow-tour-pointer-content>{children}</div>
    </Component>
  );
}

function Trigger({
  children,
  capabilityDisabled,
  label,
  marker,
  onClick,
  disabled: userDisabled,
  ...props
}: ButtonProps & {
  capabilityDisabled: boolean;
  label: string;
  marker: "back" | "cancel" | "next";
}) {
  const { binding } = useTourContext();
  const child = typeof children === "function" ? null : children;
  const childProps: React.ButtonHTMLAttributes<HTMLButtonElement> = child?.props ?? {};
  const consumerDisabled = userDisabled === true || childProps.disabled === true;
  const disabled = capabilityDisabled || consumerDisabled;

  const buttonProps: React.ButtonHTMLAttributes<HTMLButtonElement> & {
    "data-glow-tour-back-trigger": true | undefined;
    "data-glow-tour-cancel-trigger": true | undefined;
    "data-glow-tour-consumer-disabled": "true" | undefined;
    "data-glow-tour-next-trigger": true | undefined;
  } = {
    ...props,
    "aria-controls": binding?.ids.popover,
    "aria-label": props["aria-label"] || label,
    "aria-disabled": disabled ? "true" : "false",
    "data-glow-tour-back-trigger": marker === "back" || undefined,
    "data-glow-tour-cancel-trigger": marker === "cancel" || undefined,
    "data-glow-tour-consumer-disabled": consumerDisabled ? "true" : undefined,
    "data-glow-tour-next-trigger": marker === "next" || undefined,
    disabled,
    onClick: (event) => {
      childProps.onClick?.(event);
      onClick?.(event);
    },
    type: "button",
  };

  if (typeof children === "function") return children(buttonProps);
  if (child) return React.cloneElement(child, buttonProps);
  return <button {...buttonProps}>{label}</button>;
}

export function BackTrigger({ backLabel, ...props }: BackTriggerProps) {
  const { tour } = useTourContext();
  const snapshot = useTourSnapshot(tour);
  const step = useStep(snapshot);
  if (snapshot.isFirstStep || step?.hideBackButton) return null;
  const label = backLabel ?? "Back step";
  return (
    <Trigger
      {...props}
      capabilityDisabled={!snapshot.canPrevious || step?.disableBackButton === true}
      label={label}
      marker="back"
    />
  );
}

export function NextTrigger({ finishLabel, nextLabel, ...props }: NextTriggerProps) {
  const { tour } = useTourContext();
  const snapshot = useTourSnapshot(tour);
  const step = useStep(snapshot);
  if (step?.hideNextButton) return null;
  const label = snapshot.isLastStep ? (finishLabel ?? "Finish tour") : (nextLabel ?? "Next step");
  return (
    <Trigger
      {...props}
      capabilityDisabled={!snapshot.canAdvance || step?.disableNextButton === true}
      label={label}
      marker="next"
    />
  );
}

export function CancelTrigger(props: CancelTriggerProps) {
  const { tour } = useTourContext();
  const snapshot = useTourSnapshot(tour);
  if (!snapshot.canCancel) return null;
  return (
    <Trigger
      {...props}
      capabilityDisabled={!snapshot.canCancel}
      label="Cancel tour"
      marker="cancel"
    />
  );
}

export const GlowTour = {
  Root,
  Popover,
  Header,
  Content,
  Footer,
  Overlay,
  Pointer,
  BackTrigger,
  NextTrigger,
  CancelTrigger,
};
