// apps/ssr-vue/app/app.vue
<script setup lang="ts">
// biome-ignore lint/correctness/noUnusedImports: used in template
import { createGlowTour, GlowTourDefault } from "@glowhop/vue-tour";

const tour = createGlowTour();
const workflow = tour
  .create("welcome")
  .step({
    content: "This step is rendered by the SSR verification harness.",
    target: "#tour-target",
    title: "Step one",
  })
  .step({
    content: "Clicking advance again finishes the tour.",
    target: "#tour-trigger",
    title: "Step two",
  })
  .build();

// biome-ignore lint/correctness/noUnusedVariables: used in template
function start() {
  void tour.run(workflow);
}
</script>

<template>
  <div style="padding: 20px">
    <h1>Glow Tour - SSR Vue (Nuxt) verification harness</h1>
    <p id="tour-target">This is the tour target element.</p>
    <button id="tour-trigger" type="button" @click="start">Start tour</button>
  </div>
  <GlowTourDefault :tour="tour" />
</template>

// apps/ssr-react/app/page.tsx
"use client";

import { createGlowTour, DefaultTour } from "@glowhop/react-tour";
import { useState } from "react";

export default function Page() {
  const [tour] = useState(() => createGlowTour());
  const [workflow] = useState(() =>
    tour
      .create("ssr-demo")
      .step({
        target: "#step-one-target",
        title: "Step One",
        content: "This step is rendered on the server and hydrated on the client.",
      })
      .step({
        target: "#step-two-target",
        title: "Step Two",
        content: "Advancing moved the tour to this second step.",
      })
      .build(),
  );

  return (
    <main style={{ padding: 40, fontFamily: "sans-serif" }}>
      <h1>Glow Tour SSR verification (Next.js / React)</h1>
      <p>
        This page exists to prove <code>@glowhop/react-tour</code> server-renders and hydrates
        correctly inside a real Next.js app.
      </p>
      <button
        id="start-tour-trigger"
        type="button"
        onClick={() => void tour.run(workflow)}
        style={{ padding: "10px 20px", fontSize: 16 }}
      >
        Start tour
      </button>
      <div style={{ display: "flex", gap: 24, marginTop: 40 }}>
        <div id="step-one-target" style={{ padding: 16, border: "1px solid #ccc" }}>
          Target one
        </div>
        <div id="step-two-target" style={{ padding: 16, border: "1px solid #ccc" }}>
          Target two
        </div>
      </div>
      <DefaultTour tour={tour} />
    </main>
  );
}
