// packages/solid/src/components/tour-components.ts
import type { DynamicStepProps, WorkflowState } from "@glowhop/core-tour";
import {
  createComponent,
  createEffect,
  createSignal,
  type JSX,
  mergeProps,
  onCleanup,
  type ParentProps,
  Show,
  splitProps,
  type ValidComponent,
} from "solid-js";
import { Dynamic } from "solid-js/web";
import type { SolidTourContent } from "../glow-tour";
import { glowTour } from "../glow-tour";

type ElementProps = ParentProps<
  JSX.HTMLAttributes<HTMLElement> & {
    as?: ValidComponent;
  }
>;
type ContentProps = Omit<JSX.HTMLAttributes<HTMLElement>, "children">;
type FooterProps = ParentProps<JSX.HTMLAttributes<HTMLElement>>;
type OverlayProps = ParentProps<Omit<JSX.SvgSVGAttributes<SVGSVGElement>, "ref">>;
type PointerProps = ParentProps<
  Omit<JSX.HTMLAttributes<HTMLElement>, "aria-hidden"> & {
    as?: ValidComponent;
  }
>;
type ButtonProps = Omit<JSX.ButtonHTMLAttributes<HTMLButtonElement>, "children" | "type"> & {
  children?: JSX.Element | ((props: JSX.ButtonHTMLAttributes<HTMLButtonElement>) => JSX.Element);
};
type BackTriggerProps = ButtonProps & { backLabel?: string };
type NextTriggerProps = ButtonProps & { finishLabel?: string; nextLabel?: string };

const POPOVER_ID = "glow-tour-popover";
const TITLE_ID = "glow-tour-title";
const DESCRIPTION_ID = "glow-tour-description";

function useTourSnapshot() {
  const [snapshot, setSnapshot] = createSignal<WorkflowState<SolidTourContent>>(
    glowTour.state.get(),
  );
  const unsubscribe = glowTour.state.subscribe(setSnapshot);
  onCleanup(unsubscribe);
  return snapshot;
}

function useCurrentStepProps() {
  const snapshot = useTourSnapshot();
  const [stepProps, setStepProps] = createSignal<DynamicStepProps<SolidTourContent>>({
    content: null,
    title: null,
  });

  createEffect(() => {
    const step = snapshot().currentStep;
    if (!step) {
      setStepProps({ content: null, title: null });
      return;
    }

    setStepProps(step.currentProps.get());
    onCleanup(step.currentProps.subscribe(setStepProps));
  });

  return stepProps;
}

export function Root(props: ParentProps): JSX.Element {
  return props.children;
}

export function Popover(props: ElementProps): JSX.Element {
  const [local, other] = splitProps(props, [
    "as",
    "children",
    "aria-describedby",
    "aria-labelledby",
    "id",
    "role",
  ]);
  onCleanup(() => glowTour.state.registerElementPopover(null));

  return createComponent(
    Dynamic,
    mergeProps(other, {
      get component() {
        return local.as ?? "section";
      },
      get "aria-describedby"() {
        return local["aria-describedby"] ?? DESCRIPTION_ID;
      },
      get "aria-labelledby"() {
        return local["aria-labelledby"] ?? TITLE_ID;
      },
      "data-glow-tour-popover": "",
      get id() {
        return local.id ?? POPOVER_ID;
      },
      ref: (element: HTMLElement) => glowTour.state.registerElementPopover(element),
      role: local.role ?? "dialog",
      tabIndex: -1,
      get children() {
        return local.children;
      },
    }),
  );
}

export function Header(props: ContentProps): JSX.Element {
  const stepProps = useCurrentStepProps();
  return createComponent(
    Dynamic,
    mergeProps(props, {
      component: "header",
      "data-glow-tour-header": "",
      get id() {
        return props.id ?? TITLE_ID;
      },
      get children() {
        return stepProps().title;
      },
    }),
  );
}

export function Content(props: ContentProps): JSX.Element {
  const stepProps = useCurrentStepProps();
  return createComponent(
    Dynamic,
    mergeProps(props, {
      get "aria-live"() {
        return props["aria-live"] ?? "polite";
      },
      component: "div",
      "data-glow-tour-content": "",
      get id() {
        return props.id ?? DESCRIPTION_ID;
      },
      get children() {
        return stepProps().content;
      },
    }),
  );
}

export function Footer(props: FooterProps): JSX.Element {
  const stepProps = useCurrentStepProps();
  return Show({
    get when() {
      return !stepProps().hideFooter;
    },
    get children() {
      return createComponent(
        Dynamic,
        mergeProps(props, {
          component: "footer",
          "data-glow-tour-footer": "",
          get children() {
            return props.children;
          },
        }),
      );
    },
  });
}

export function Overlay(props: OverlayProps): JSX.Element {
  const [local, other] = splitProps(props, ["aria-hidden", "children", "viewBox"]);
  onCleanup(() => glowTour.state.registerElementOverlay(null));

  const path = createComponent(Dynamic, {
    component: "path",
    "data-glow-tour-overlay-path": "",
    "fill-rule": "evenodd",
  });

  return createComponent(
    Dynamic,
    mergeProps(other, {
      get "aria-hidden"() {
        return local["aria-hidden"] ?? true;
      },
      component: "svg",
      "data-glow-tour-overlay": "",
      focusable: "false",
      ref: (element: SVGSVGElement) => glowTour.state.registerElementOverlay(element),
      role: "presentation",
      get viewBox() {
        return local.viewBox ?? "0 0 0 0";
      },
      get children() {
        return [path, local.children];
      },
    }),
  );
}

export function Pointer(props: PointerProps): JSX.Element {
  const [local, other] = splitProps(props, ["as", "children"]);
  onCleanup(() => glowTour.state.registerElementPointer(null));

  const content = createComponent(Dynamic, {
    component: "div",
    "data-glow-tour-pointer-content": "",
    get children() {
      return local.children;
    },
  });

  return createComponent(
    Dynamic,
    mergeProps(other, {
      get component() {
        return local.as ?? "div";
      },
      "aria-hidden": "true",
      "data-glow-tour-pointer": "",
      ref: (element: HTMLElement) => glowTour.state.registerElementPointer(element),
      children: content,
    }),
  );
}

export function BackTrigger(props: BackTriggerProps): JSX.Element {
  const [local, other] = splitProps(props, [
    "aria-controls",
    "aria-label",
    "backLabel",
    "children",
  ]);
  const snapshot = useTourSnapshot();
  const stepProps = useCurrentStepProps();
  const label = () =>
    local.backLabel ?? snapshot().startOptions.popover?.buttons?.backLabel ?? "Back step";
  const buttonProps = mergeProps(
    {
      get "aria-controls"() {
        return local["aria-controls"] ?? POPOVER_ID;
      },
      get "aria-label"() {
        return local["aria-label"] ?? label();
      },
      "data-action": "back",
      "data-glow-tour-back-trigger": true,
      get disabled() {
        return !snapshot().canGoBack || stepProps().disableBackButton;
      },
      onClick(event: MouseEvent) {
        event.preventDefault();
        void glowTour.state.back();
      },
      type: "button" as const,
    },
    other,
  );

  return Show({
    get when() {
      return !snapshot().isFirstStep && !stepProps().hideBackButton;
    },
    get children() {
      if (typeof local.children === "function") return local.children(buttonProps);
      return createComponent(
        Dynamic,
        mergeProps(buttonProps, {
          component: "button",
          get children() {
            return local.children ?? label();
          },
        }),
      );
    },
  });
}

export function NextTrigger(props: NextTriggerProps): JSX.Element {
  const [local, other] = splitProps(props, [
    "aria-controls",
    "aria-label",
    "children",
    "finishLabel",
    "nextLabel",
  ]);
  const snapshot = useTourSnapshot();
  const stepProps = useCurrentStepProps();
  const label = () => {
    const labels = snapshot().startOptions.popover?.buttons;
    return snapshot().isLastStep
      ? (local.finishLabel ?? labels?.finishLabel ?? "Finish tour")
      : (local.nextLabel ?? labels?.nextLabel ?? "Next step");
  };
  const buttonProps = mergeProps(
    {
      get "aria-controls"() {
        return local["aria-controls"] ?? POPOVER_ID;
      },
      get "aria-label"() {
        return local["aria-label"] ?? label();
      },
      "data-action": "next",
      "data-glow-tour-next-trigger": true,
      get disabled() {
        return !snapshot().canGoNext || stepProps().disableNextButton;
      },
      onClick(event: MouseEvent) {
        event.preventDefault();
        void glowTour.state.next();
      },
      type: "button" as const,
    },
    other,
  );

  return Show({
    get when() {
      return !stepProps().hideNextButton;
    },
    get children() {
      if (typeof local.children === "function") return local.children(buttonProps);
      return createComponent(
        Dynamic,
        mergeProps(buttonProps, {
          component: "button",
          get children() {
            return local.children ?? label();
          },
        }),
      );
    },
  });
}

export const GlowTour = {
  Root,
  Popover,
  Header,
  Content,
  Footer,
  Overlay,
  Pointer,
  BackTrigger,
  NextTrigger,
};

// packages/angular/src/lib/components/tour-components.ts
import { NgTemplateOutlet } from "@angular/common";
import {
  Component,
  computed,
  type ElementRef,
  Input,
  signal,
  TemplateRef,
  ViewChild,
} from "@angular/core";
import type { DynamicStepProps, WorkflowState } from "@glowhop/core-tour";
import type { AngularTourContent } from "../glow-tour";
import { glowTour } from "../glow-tour";

const POPOVER_ID = "glow-tour-popover";

export const GLOW_TOUR_COMPONENT_TEMPLATES = {
  root: "<section data-glow-tour-root><ng-content /></section>",
  header:
    '<header data-glow-tour-header id="glow-tour-title">@if (titleTemplate()) { <ng-container [ngTemplateOutlet]="titleTemplate()" /> } @else { {{ titleText() }} }</header>',
  content:
    '<div data-glow-tour-content id="glow-tour-description" aria-live="polite">@if (contentTemplate()) { <ng-container [ngTemplateOutlet]="contentTemplate()" /> } @else { {{ contentText() }} }</div>',
  footer: "@if (!stepProps().hideFooter) { <footer data-glow-tour-footer><ng-content /></footer> }",
  popover:
    '<section #tourElement data-glow-tour-popover id="glow-tour-popover" tabindex="-1" role="dialog" aria-labelledby="glow-tour-title" aria-describedby="glow-tour-description"><ng-content /></section>',
  pointer:
    '<div #tourElement data-glow-tour-pointer aria-hidden="true"><div data-glow-tour-pointer-content><ng-content /></div></div>',
  overlay:
    '<svg #tourElement data-glow-tour-overlay aria-hidden="true" role="presentation" focusable="false" viewBox="0 0 0 0"><path data-glow-tour-overlay-path fill-rule="evenodd" /><ng-content /></svg>',
  backTrigger:
    '@if (!isHidden()) { <button type="button" data-action="back" data-glow-tour-back-trigger [attr.aria-label]="ariaLabel || label()" [attr.aria-controls]="ariaControls" [disabled]="isDisabled()" (click)="back($event)"><ng-content>{{ label() }}</ng-content></button> }',
  nextTrigger:
    '@if (!isHidden()) { <button type="button" data-action="next" data-glow-tour-next-trigger [attr.aria-label]="ariaLabel || label()" [attr.aria-controls]="ariaControls" [disabled]="isDisabled()" (click)="next($event)"><ng-content>{{ label() }}</ng-content></button> }',
} as const;

abstract class GlowTourReactiveComponent {
  readonly snapshot = signal<WorkflowState<AngularTourContent>>(glowTour.state.get());
  readonly stepProps = signal<DynamicStepProps<AngularTourContent>>({ content: "", title: "" });
  private stepCleanup?: () => void;
  private readonly stateCleanup: () => void;

  constructor() {
    this.syncState(glowTour.state.get());
    this.stateCleanup = glowTour.state.subscribe((state) => this.syncState(state));
  }

  private syncState(state: WorkflowState<AngularTourContent>) {
    this.snapshot.set(state);
    this.stepCleanup?.();
    this.stepCleanup = undefined;
    const step = state.currentStep;
    if (!step) {
      this.stepProps.set({ content: "", title: "" });
      return;
    }
    this.stepProps.set(step.currentProps.get());
    this.stepCleanup = step.currentProps.subscribe((value) => this.stepProps.set(value));
  }

  ngOnDestroy() {
    this.stepCleanup?.();
    this.stateCleanup();
  }
}

@Component({
  selector: "glow-tour-root",
  standalone: true,
  template: GLOW_TOUR_COMPONENT_TEMPLATES.root,
})
export class GlowTourRoot {}

@Component({
  selector: "glow-tour-header",
  standalone: true,
  imports: [NgTemplateOutlet],
  template: GLOW_TOUR_COMPONENT_TEMPLATES.header,
})
export class GlowTourHeader extends GlowTourReactiveComponent {
  readonly titleTemplate = computed(() => {
    const value = this.stepProps().title;
    return value instanceof TemplateRef ? value : null;
  });
  readonly titleText = computed(() => {
    const value = this.stepProps().title;
    return typeof value === "string" ? value : "";
  });
}

@Component({
  selector: "glow-tour-content",
  standalone: true,
  imports: [NgTemplateOutlet],
  template: GLOW_TOUR_COMPONENT_TEMPLATES.content,
})
export class GlowTourContent extends GlowTourReactiveComponent {
  readonly contentTemplate = computed(() => {
    const value = this.stepProps().content;
    return value instanceof TemplateRef ? value : null;
  });
  readonly contentText = computed(() => {
    const value = this.stepProps().content;
    return typeof value === "string" ? value : "";
  });
}

@Component({
  selector: "glow-tour-footer",
  standalone: true,
  template: GLOW_TOUR_COMPONENT_TEMPLATES.footer,
})
export class GlowTourFooter extends GlowTourReactiveComponent {}

@Component({
  selector: "glow-tour-popover",
  standalone: true,
  template: GLOW_TOUR_COMPONENT_TEMPLATES.popover,
})
export class GlowTourPopover {
  @ViewChild("tourElement", { static: true }) private readonly element!: ElementRef<HTMLElement>;

  ngAfterViewInit() {
    glowTour.state.registerElementPopover(this.element.nativeElement);
  }

  ngOnDestroy() {
    glowTour.state.registerElementPopover(null);
  }
}

@Component({
  selector: "glow-tour-pointer",
  standalone: true,
  template: GLOW_TOUR_COMPONENT_TEMPLATES.pointer,
})
export class GlowTourPointer {
  @ViewChild("tourElement", { static: true }) private readonly element!: ElementRef<HTMLElement>;

  ngAfterViewInit() {
    glowTour.state.registerElementPointer(this.element.nativeElement);
  }

  ngOnDestroy() {
    glowTour.state.registerElementPointer(null);
  }
}

@Component({
  selector: "glow-tour-overlay",
  standalone: true,
  template: GLOW_TOUR_COMPONENT_TEMPLATES.overlay,
})
export class GlowTourOverlay {
  @ViewChild("tourElement", { static: true }) private readonly element!: ElementRef<SVGSVGElement>;

  ngAfterViewInit() {
    glowTour.state.registerElementOverlay(this.element.nativeElement);
  }

  ngOnDestroy() {
    glowTour.state.registerElementOverlay(null);
  }
}

@Component({
  selector: "glow-tour-back-trigger",
  standalone: true,
  template: GLOW_TOUR_COMPONENT_TEMPLATES.backTrigger,
})
export class GlowTourBackTrigger extends GlowTourReactiveComponent {
  @Input() ariaControls = POPOVER_ID;
  @Input() ariaLabel?: string;
  @Input() backLabel?: string;

  readonly isHidden = computed(
    () => this.snapshot().isFirstStep || this.stepProps().hideBackButton === true,
  );
  readonly isDisabled = computed(
    () => !this.snapshot().canGoBack || this.stepProps().disableBackButton === true,
  );
  readonly label = computed(
    () => this.backLabel ?? this.snapshot().startOptions.popover?.buttons?.backLabel ?? "Back step",
  );

  back(event: Event) {
    event.preventDefault();
    void glowTour.state.back();
  }
}

@Component({
  selector: "glow-tour-next-trigger",
  standalone: true,
  template: GLOW_TOUR_COMPONENT_TEMPLATES.nextTrigger,
})
export class GlowTourNextTrigger extends GlowTourReactiveComponent {
  @Input() ariaControls = POPOVER_ID;
  @Input() ariaLabel?: string;
  @Input() finishLabel?: string;
  @Input() nextLabel?: string;

  readonly isHidden = computed(() => this.stepProps().hideNextButton === true);
  readonly isDisabled = computed(
    () => !this.snapshot().canGoNext || this.stepProps().disableNextButton === true,
  );
  readonly label = computed(() => {
    const labels = this.snapshot().startOptions.popover?.buttons;
    return this.snapshot().isLastStep
      ? (this.finishLabel ?? labels?.finishLabel ?? "Finish tour")
      : (this.nextLabel ?? labels?.nextLabel ?? "Next step");
  });

  next(event: Event) {
    event.preventDefault();
    void glowTour.state.next();
  }
}
